### PR TITLE
Add error handling for bad directory

### PR DESCRIPTION
**Pull request by shubham1172**
Solves https://github.com/microsoft/fabrikate/issues/156. 

If the directory doesn't exist or the user doesn't have permissions to access it, an error will be logged and returned to the caller.

### CODE REVIEW

**Comment by shubham1172** [comment]
Should I write a test case to cover it too? The generator can simply fail if the directory is missing.

**Comment by timfpark** [comment]
Thank you @shubham1172.  Yes, please add a test to cover this functionality.

**Comment by shubham1172** [comment]
Added a test!

**Comment by timfpark** [comment]
Looks good to me - thanks so much for your contribution - its much appreciated.

**Pull request merged**
