### PR TITLE
Add capability to disable subcomponent per environment

### LINKED ISSUE #277: Ability to include / exclude subcomponents based on config
As an operator I would like to dynamically be able to include or exclude components based on configuration.  For example, if I had a very large number of distributed locations and wanted to enable app A in 20% of them and app B in 80% of them.

Right now, Fabrikate does not have a mechanism to accomplish this with configuration.  This issue tracks the ability to enable or disable components or subcomponents based on config.

### PR DESCRIPTION
**Pull request by marcel-dias**
# Add capability to disable subcomponent per environment

I'm really interested in this feature so opening this PR to contribute.
From the issue #277 I have preferred the property `disabled`  over excluded.

## what I changed
I'm proposing the addition of a disabled attribute to the Subcomponents Config. 
The default value is `false` so all subcomponents will be enabled by default.

Basically we will be able to disabled components per environment:

```yaml
..config/myenv.yaml..

subcomponents:
  my-subcomponent:
    disabled: true
```

closes #277

### CODE REVIEW

**Comment by joushx** [comment]
Somehow this does not work for me. A component that is set to disabled in my config is still generated.

**Comment by marceldiass** [comment]
hey @joushx 

I have created this gist with a stack example https://gist.github.com/marceldiass/9c72a4c7a17a524d8f6265db121a8ddd

the `disabled` property should be used in the files inside `config` folder.

```
config/
      local.yaml
      disabled.yaml
component.yaml
```

**Comment by evanlouie** [comment]
Hi @marceldiass, thanks for the PR!
I took a look at your gist and while it works for the example you provided, if I modify the component.yaml to:

```yaml
name: my-stack
type: component
subcomponents:
  - name: pod-info
    type: helm
    method: git
    source: https://github.com/stefanprodan/podinfo
    path: charts/podinfo
  - name: elasticsearch
    type: helm
    method: git
    source: https://github.com/helm/charts
    path: stable/elasticsearch
  - name: mysql
    type: helm
    method: git
    source: https://github.com/helm/charts
    path: stable/mysql
  - name: bookinfo # Istio BookInfo application - wrapped in Fabrikate component
    source: https://github.com/microsoft/fabrikate-definitions.git
    path: definitions/fabrikate-bookinfo
    method: git
```

and the `config/disabled.yaml` to:

```yaml
subcomponents:
  pod-info:
    config:
      env: local
  elasticsearch:
    disabled: true
    config:
      env: local
  mysql:
    disabled: true
    config:
      env: local
  bookinfo:
    disabled: true
```

`fab generate disabled` still renders the `bookinfo` component. Think we'll need to iron this out before merging

**Comment by marcel-dias** [comment]
Hey @evanlouie 

I found the issue. Added Generate test to cover that scenario.
Basically when subcomponent is `component` type it overrides the configs from the main component.  

I'm not sure what is failing in the build as I can't see logs. Weird part is I forked the repo to mine Azure devops org and there build is passing with exactly same pipeline definition.

Could you help me find the build issue ?

**Comment by evanlouie** [comment]
@marcel-dias Re-ran the the build pipeline (after some recent changes made it into `develop`) and things are looking good. Thanks so much for your contribution :)

**Comment by hidetran** [comment]
@marcel-dias  Could you please update or grant access to sample at https://gist.github.com/marceldiass/9c72a4c7a17a524d8f6265db121a8ddd, since I've no access (404) to this.

I tried to disabled component per environment but failed. This is my implementation:
```yaml
config
  dev.yaml
  prod.yaml
  common.yaml

book
  admin
  enduser
  config
     common.yaml
  component.yaml

shop
  admin
  enduser
  config
     common.yaml
component.yaml
```

I want to disable subcomponents named **admin**, **enduser** in component **book** when generate fab folder **dev**, but don't know where to put disabled.yaml file

**Comment by marcel-dias** [comment]
> @marcel-dias @evanlouie Could you please update or grant access to sample at https://gist.github.com/marceldiass/9c72a4c7a17a524d8f6265db121a8ddd, since I've no access (404) to this.
> 
> I tried to disabled component per environment but failed. This is my implementation:
> 
> ```yaml
> config
>   dev.yaml
>   prod.yaml
>   common.yaml
> 
> book
>   admin
>   enduser
>   config
>      common.yaml
>   component.yaml
> 
> shop
>   admin
>   enduser
>   config
>      common.yaml
> component.yaml
> ```
> 
> I want to disable subcomponents named **admin**, **enduser** in component **book** when generate fab folder **dev**, but don't know where to put disabled.yaml file

Hey @hidetran  
You can find the gist in this link https://gist.github.com/marcel-dias/9c72a4c7a17a524d8f6265db121a8ddd

**Comment by hidetran** [comment]
@marcel-dias 
Thank you for that, I've able to disable component, do you have any information when this feature is ready for release yet ?

**Comment by marcel-dias** [comment]
@hidetran I'm also waiting for this to be released. Not sure which is the proper way to talk to the maintainers.

**Comment by hidetran** [comment]
@marcel-dias 

Thank again for this feature, I am looking the way to force use this feature by modify build.sh to allow specified branch of fabrikate.

**Pull request merged**
