### PR TITLE
Add 'set' command to enable easily setting configuration values.

### PR DESCRIPTION
**Pull request by timfpark**
Closes https://github.com/Microsoft/fabrikate/issues/84 and works toward https://github.com/Microsoft/fabrikate/issues/30 on the config front.

### CODE REVIEW

**Comment by timfpark** [comment]
@dtzar 

For #1, You can string together multiple pathValue items on the command line to add multiple configs. eg. 

```
$ fab set --environment staging app1.imageTag=foo:121 app2.imageTag=bar:343 
```

#2:  Great idea, I added that.
#3:  Also great idea, I will add an issue for that one as an enhancement.

**Comment by timfpark** [comment]
For #3, I added https://github.com/Microsoft/fabrikate/issues/87 to track.

**Comment by dtzar** [comment]
For #1 I was thinking of more of this case:
`fab set --environment staging imageTag=foo:121`
where per your above example there are two different `imageTag` values in different sub-directories.

**Comment by timfpark** [comment]
Ok - for #1, can you open an issue with a proposal for what the CLI user interface would look like for that and we can talk through it in that issue and treat that also like an enhancement?

**Comment by dtzar** [comment]
Added item https://github.com/Microsoft/fabrikate/issues/95

**Pull request merged**
